<a href="https://colab.research.google.com/github/Aslbekjon/data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
my_list = list(range(100000)) #python list 0~99990 -- > Normal
my_array = np.array(range(100000)) # numpy array(massiv) 0~99999 --> Vektorlashgan 

In [ ]:
%time for _ in range(10): [x*2 for x in my_list]

CPU times: user 63.9 ms, sys: 0 ns, total: 63.9 ms
Wall time: 69.9 ms


In [ ]:
%time for _ in range(10): my_array*2 #Vektorlashgan

CPU times: user 1.13 ms, sys: 12 µs, total: 1.14 ms
Wall time: 1.15 ms


In [ ]:
131/6.06

21.61716171617162

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
arr1


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2 = np.zeros((2,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr3 = np.ones((2,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr4 = np.arange(4,40,3)
arr4

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [ ]:
%time arr5 = np.arange(1,100)

CPU times: user 30 µs, sys: 0 ns, total: 30 µs
Wall time: 33.4 µs


In [ ]:
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
ln = len(arr5)

In [ ]:
arr6 = np.zeros((2,4))

In [ ]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr7 = np.random.randint(5, size=(2,4))

In [ ]:
arr7

array([[1, 4, 2, 1],
       [4, 0, 1, 1]])

In [ ]:
arr8 = np.random.randn(2,4)

In [ ]:
arr8

array([[ 0.0829713 , -0.47576141,  0.89668016, -0.45146291],
       [-2.1196157 ,  0.77868118, -1.42768599,  0.26002987]])

In [ ]:
arr9 = np.random.rand(2,4)

In [ ]:
arr9

array([[0.54103927, 0.52589481, 0.57606156, 0.88144576],
       [0.76892223, 0.61972909, 0.18686063, 0.3838377 ]])

In [ ]:
arr10 = np.random.randint(10,19, size=(2,4))

In [ ]:
arr10

array([[15, 13, 12, 10],
       [15, 16, 16, 13]])

In [ ]:
arr11 = np.array([1,2,3,4], dtype=np.float64)

In [ ]:
arr11

array([1., 2., 3., 4.])

In [ ]:
arr11.dtype

dtype('float64')

In [ ]:
arr11 = arr11.astype(np.int64)

In [ ]:
arr11

array([1, 2, 3, 4])

In [ ]:
arr11.dtype

dtype('int64')

In [ ]:
arra = np.arange(10)
arra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arra[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arra[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arr21 = np.array([np.arange(4),np.arange(4)])
arr21

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
arr21[0,0]

0

In [ ]:
arr21[1,2]

2

In [ ]:
arr22 = np.array([[np.arange(1,4),np.arange(1,4), np.arange(1,4)],[np.arange(1,4),np.arange(1,4), np.arange(1,4)],[np.arange(1,4),np.arange(1,4), np.arange(1,4)]])
arr22

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [ ]:
arr22[1][1,1]

2

In [ ]:
arr = [[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],

               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],

               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]]
d = arr[1]

In [ ]:
d

[[9, 10, 11], [12, 13, 14], [15, 16, 17]]

In [ ]:
d[1]

[12, 13, 14]

In [ ]:
d[1][1]

13

In [ ]:
arr[1][1][1]

13

In [ ]:
arr[1][1][:2]

[12, 13]

In [ ]:
arr


[[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
 [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
 [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]

In [ ]:
names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
data = np.array([[5, 6, 1, 1],
[9, 1, 1, 1],
[7, 7, 4, 2],
[1, 5, 1, 9],
[9, 9, 4, 5],
[7, 5, 9, 6],
[5, 3, 7, 4]])
data[(names=='Javohir') | (names=='Elyor')]

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [5]:
A = np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [7]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.swapaxes(1,0)

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
np.dot(A,A.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [12]:
arr1 = np.random.randn(6)
arr2 = np.random.randn(6)
print(arr1)
print(arr2)

[ 0.0958444   0.70585528  1.34437142 -0.61820118  1.08150037  0.30739707]
[ 1.38356479 -0.17031826 -0.3993463   0.5869193  -1.73935218  0.18292355]


In [14]:
cr = np.array([True, False, True, True, False, False])
np.where(cr,arr1,arr2)

array([ 0.0958444 , -0.17031826,  1.34437142, -0.61820118, -1.73935218,
        0.18292355])

In [15]:
np.where(arr1>0,2,-2)

array([ 2,  2,  2, -2,  2,  2])

In [16]:
arr1+arr2

array([ 1.4794092 ,  0.53553702,  0.94502512, -0.03128188, -0.65785181,
        0.49032062])

In [17]:
arr1-arr2

array([-1.28772039,  0.87617354,  1.74371772, -1.20512048,  2.82085255,
        0.12447351])

In [18]:
arr1*arr2

array([ 0.13260694, -0.12022004, -0.53686975, -0.3628342 , -1.88111003,
        0.05623016])

In [19]:
arr1/arr2

array([ 0.06927352, -4.14433114, -3.36643015, -1.05329843, -0.62178343,
        1.6804674 ])

In [20]:
arr3 = np.random.randn(4,5)
arr3

array([[-0.5760201 , -0.24844335,  0.86980613, -0.56587035,  1.11417843],
       [ 0.94580005, -0.01251611,  0.89982049,  0.54553972, -0.41732999],
       [-1.32980719,  0.4139477 , -0.81826135, -0.34904915,  0.21632789],
       [-0.60150222, -1.05499396,  0.79877418,  0.82749424,  0.65653417]])

In [21]:
arr3.sum()

1.3144292207359722

In [23]:
np.square(arr3)

array([[3.31799155e-01, 6.17240999e-02, 7.56562695e-01, 3.20209252e-01,
        1.24139357e+00],
       [8.94537738e-01, 1.56652965e-04, 8.09676905e-01, 2.97613590e-01,
        1.74164323e-01],
       [1.76838715e+00, 1.71352695e-01, 6.69551631e-01, 1.21835312e-01,
        4.67977554e-02],
       [3.61804924e-01, 1.11301225e+00, 6.38040188e-01, 6.84746715e-01,
        4.31037119e-01]])

In [24]:
np.sum(arr3,axis=1)

array([ 0.59365075,  1.96131416, -1.8668421 ,  0.62630641])

In [25]:
arr4 = np.arange(6)

In [26]:
arr4

array([0, 1, 2, 3, 4, 5])

In [27]:
arr4.sum()

15

In [28]:
arr5 = np.array([np.arange(6), np.arange(6,12)])
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
arr5.sum(axis=1)

array([15, 51])

In [30]:
arr5.sum(axis=0)

array([ 6,  8, 10, 12, 14, 16])

In [31]:
arr5.mean()   #o'rtacha qiymat

5.5

In [32]:
arr5.mean(axis=1)

array([2.5, 8.5])

In [33]:
arr5.mean(axis=0)

array([3., 4., 5., 6., 7., 8.])

In [34]:
arr5.cumsum()  #o'zigacha bo'lgan qiymatlari yigindisini mos ravishda

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [35]:
arr5.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10, 15],
       [ 6, 13, 21, 30, 40, 51]])

In [36]:
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [37]:
arr5.sort(axis=1)

In [38]:
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [39]:
arr = -np.sort(-arr5, axis=1)
arr

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6]])

In [40]:
names = np.array(['Aslbek', 'Komila', 'Marjona', 'Dilbar', 'Marjona', 'Dilbar'])
ints = np.array([3,3,3,2,2,1,1,4,4])

In [41]:
np.unique(names)

array(['Aslbek', 'Dilbar', 'Komila', 'Marjona'], dtype='<U7')

In [42]:
arr1 = np.array([6, 0, 0, 3, 2, 5, 6])
arr2 = np.array([0, 2, 3])

In [43]:
np.in1d(arr1,arr2)

array([False,  True,  True,  True,  True, False, False])

In [47]:
names1 = np.array(['Aslbek', 'Abdurahmon', 'Hasan',  'Konila', 'Sarvar', 'Temur'])
names2 = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])

In [48]:
np.setdiff1d(names1, names2) # names1 massivining names2 massividagi takrorlanmas qismini qaytaradi

array(['Aslbek', 'Konila'], dtype='<U10')

In [49]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a+b
c = c*a
print(c[2])

21


In [51]:
a = np.array([[1,2],[3,4]])
print(a.itemsize)

8
